FROM python:3.12

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app

# Expose the port uvicorn will run on
EXPOSE 80

# --reload for hot reload on changes to the code
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]

# docker build -t talos -f Dockerfile.dev .
# docker run -it --name talos -p 80:80 -v ${pwd}/app:/code/app talos