name: Fly Deploy
on:
    push:
        branches:
            - main # change to main if needed
jobs:
    deploy:
        name: Deploy app
        runs-on: ubuntu-latest
        concurrency: deploy-group # optional: ensure only one action runs at a time
        steps:
            - uses: actions/checkout@v4
            - uses: superfly/flyctl-actions/setup-flyctl@master

            # Deploy Frontend (React)
            - name: Install frontend deps
              working-directory: ./frontend
              run: npm install

            - name: Run Vitest
              working-directory: ./frontend
              run: npx vitest run

            - name: Deploy Frontend
              working-directory: ./frontend
              run: flyctl deploy --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

            # Deploy Backend (FastAPI)
            - name: Deploy Backend
              working-directory: ./backend
              run: flyctl deploy --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
